import { defineArrayMember, defineField, defineType } from "sanity";

const imageFields = [
  defineField({ name: "alt", title: "Alt text", type: "string", validation: (rule) => rule.required() }),
  defineField({ name: "caption", title: "Caption", type: "string" }),
  defineField({ name: "photographer", title: "Photographer", type: "string" }),
  defineField({ name: "source", title: "Source / rights holder", type: "string" }),
  defineField({ name: "rights", title: "Rights notes", type: "text", rows: 3 }),
];

export const editorialArticleType = defineType({
  name: "article",
  title: "Articles",
  type: "document",
  groups: [
    { name: "content", title: "Article", default: true },
    { name: "seo", title: "SEO" },
    { name: "intelligence", title: "Editorial Intelligence" },
    { name: "sources", title: "Sources & Fact Ledger" },
    { name: "workflow", title: "Workflow" },
  ],
  fields: [
    defineField({ name: "title", title: "Title", type: "string", group: "content", validation: (rule) => rule.required() }),
    defineField({ name: "slug", title: "Slug", type: "slug", group: "content", options: { source: "title", maxLength: 96 }, validation: (rule) => rule.required() }),
    defineField({ name: "standfirst", title: "Standfirst", type: "text", rows: 3, group: "content", validation: (rule) => rule.required() }),
    defineField({ name: "publishedAt", title: "Published at", type: "datetime", group: "content", validation: (rule) => rule.required() }),
    defineField({ name: "updatedAt", title: "Updated at", type: "datetime", group: "content" }),
    defineField({ name: "readingTime", title: "Reading time", type: "string", group: "content" }),
    defineField({ name: "isLead", title: "Lead story", type: "boolean", group: "content", initialValue: false }),
    defineField({ name: "author", title: "Author", type: "reference", group: "content", to: [{ type: "author" }] }),
    defineField({ name: "category", title: "Category", type: "reference", group: "content", to: [{ type: "category" }], validation: (rule) => rule.required() }),
    defineField({ name: "province", title: "Province", type: "reference", group: "content", to: [{ type: "province" }] }),
    defineField({ name: "competition", title: "Competition", type: "reference", group: "content", to: [{ type: "competition" }] }),
    defineField({ name: "tags", title: "Tags", type: "array", group: "content", of: [{ type: "reference", to: [{ type: "tag" }] }] }),
    defineField({ name: "featuredImage", title: "Featured image", type: "image", group: "content", options: { hotspot: true }, fields: imageFields }),
    defineField({ name: "keyPoints", title: "Key points", type: "array", group: "content", of: [{ type: "string" }] }),
    defineField({
      name: "body",
      title: "Body",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "block" }), defineArrayMember({ type: "image", options: { hotspot: true }, fields: imageFields })],
    }),
    defineField({ name: "seoTitle", title: "SEO title", type: "string", group: "seo" }),
    defineField({ name: "seoDescription", title: "SEO description", type: "text", rows: 3, group: "seo" }),

    defineField({ name: "editorialAngle", title: "Editorial angle", type: "text", rows: 3, group: "intelligence" }),
    defineField({ name: "audiencePromise", title: "Audience promise", type: "text", rows: 3, group: "intelligence" }),
    defineField({ name: "editorialConfidence", title: "Editorial confidence (%)", type: "number", group: "intelligence", validation: (rule) => rule.min(0).max(100) }),
    defineField({ name: "needsHumanFactCheck", title: "Human fact-check required", type: "boolean", group: "intelligence" }),
    defineField({ name: "editorialDecision", title: "Editorial decision", type: "string", group: "intelligence" }),
    defineField({ name: "editorialPriority", title: "Editorial priority", type: "string", group: "intelligence" }),
    defineField({ name: "editorialStoryType", title: "Story type", type: "string", group: "intelligence" }),
    defineField({ name: "editorialGeneratedAt", title: "Generated at", type: "datetime", group: "intelligence", readOnly: true }),
    defineField({ name: "editorialInputId", title: "Editorial input ID", type: "string", group: "intelligence", readOnly: true }),
    defineField({ name: "generationDisclosure", title: "Generation disclosure", type: "text", rows: 4, group: "intelligence" }),
    defineField({ name: "generationSchemaVersion", title: "Generation schema version", type: "string", group: "intelligence", readOnly: true }),
    defineField({
      name: "editorialBrief",
      title: "Editorial brief",
      type: "object",
      group: "intelligence",
      fields: [
        defineField({ name: "angle", title: "Angle", type: "text", rows: 3 }),
        defineField({ name: "audiencePromise", title: "Audience promise", type: "text", rows: 3 }),
        defineField({ name: "keyQuestions", title: "Key questions", type: "array", of: [{ type: "string" }] }),
        defineField({ name: "requiredContext", title: "Required context", type: "array", of: [{ type: "string" }] }),
        defineField({ name: "prohibitedApproaches", title: "Prohibited approaches", type: "array", of: [{ type: "string" }] }),
      ],
    }),
    defineField({
      name: "editorialScore",
      title: "Editorial score",
      type: "object",
      group: "intelligence",
      fields: [
        defineField({ name: "total", title: "Total", type: "number" }),
        defineField({ name: "freshness", title: "Freshness", type: "number" }),
        defineField({ name: "relevance", title: "Relevance", type: "number" }),
        defineField({ name: "readerInterest", title: "Reader interest", type: "number" }),
        defineField({ name: "sourceStrength", title: "Source strength", type: "number" }),
        defineField({ name: "distinctiveness", title: "Distinctiveness", type: "number" }),
        defineField({ name: "rationale", title: "Rationale", type: "array", of: [{ type: "string" }] }),
      ],
    }),

    defineField({ name: "sourceStoryTitle", title: "Source story title", type: "string", group: "sources" }),
    defineField({ name: "sourceStorySummary", title: "Source story summary", type: "text", rows: 4, group: "sources" }),
    defineField({ name: "sourceStoryBodyText", title: "Source story body text", type: "text", rows: 6, group: "sources" }),
    defineField({ name: "sourceStoryDiscoveredAt", title: "Source story discovered at", type: "datetime", group: "sources" }),
    defineField({
      name: "sourceRecords",
      title: "Source records",
      type: "array",
      group: "sources",
      of: [{ type: "object", fields: [
        defineField({ name: "id", title: "ID", type: "string" }),
        defineField({ name: "title", title: "Title", type: "string" }),
        defineField({ name: "publisher", title: "Publisher", type: "string" }),
        defineField({ name: "url", title: "URL", type: "url" }),
        defineField({ name: "publishedAt", title: "Published at", type: "datetime" }),
        defineField({ name: "retrievedAt", title: "Retrieved at", type: "datetime" }),
        defineField({ name: "isPrimarySource", title: "Primary source", type: "boolean" }),
      ] }],
    }),
    defineField({
      name: "sourceNotes",
      title: "Source notes",
      type: "array",
      group: "sources",
      of: [{ type: "object", fields: [
        defineField({ name: "sourceId", title: "Source ID", type: "string" }),
        defineField({ name: "publisher", title: "Publisher", type: "string" }),
        defineField({ name: "url", title: "URL", type: "url" }),
        defineField({ name: "usage", title: "Usage", type: "text", rows: 3 }),
      ] }],
    }),
    defineField({
      name: "factLedger",
      title: "Fact ledger",
      type: "object",
      group: "sources",
      fields: [
        defineField({
          name: "facts",
          title: "Facts",
          type: "array",
          of: [{ type: "object", fields: [
            defineField({ name: "id", title: "ID", type: "string" }),
            defineField({ name: "claim", title: "Claim", type: "text", rows: 2 }),
            defineField({ name: "status", title: "Status", type: "string" }),
            defineField({ name: "confidence", title: "Confidence (%)", type: "number" }),
            defineField({ name: "sourceIds", title: "Source IDs", type: "array", of: [{ type: "string" }] }),
            defineField({ name: "notes", title: "Notes", type: "text", rows: 2 }),
            defineField({ name: "usableInDraft", title: "Usable in draft", type: "boolean" }),
          ] }],
        }),
        defineField({ name: "unsupportedClaims", title: "Unsupported claims", type: "array", of: [{ type: "string" }] }),
        defineField({ name: "conflicts", title: "Conflicts", type: "array", of: [{ type: "string" }] }),
      ],
    }),

    defineField({ name: "workflowStatus", title: "Workflow status", type: "string", group: "workflow" }),
    defineField({ name: "workflowUpdatedAt", title: "Workflow updated at", type: "datetime", group: "workflow", readOnly: true }),
    defineField({ name: "rejectionReason", title: "Rejection reason", type: "text", rows: 3, group: "workflow" }),
    defineField({ name: "rejectionCount", title: "Rejection count", type: "number", group: "workflow", readOnly: true }),
    defineField({ name: "replacementRequired", title: "Replacement required", type: "boolean", group: "workflow", readOnly: true }),
    defineField({
      name: "workflowHistory",
      title: "Workflow history",
      type: "array",
      group: "workflow",
      readOnly: true,
      of: [{ type: "object", fields: [
        defineField({ name: "action", title: "Action", type: "string" }),
        defineField({ name: "fromStatus", title: "From status", type: "string" }),
        defineField({ name: "toStatus", title: "To status", type: "string" }),
        defineField({ name: "actor", title: "Actor", type: "string" }),
        defineField({ name: "note", title: "Note", type: "text", rows: 2 }),
        defineField({ name: "occurredAt", title: "Occurred at", type: "datetime" }),
      ] }],
    }),
  ],
  preview: {
    select: { title: "title", subtitle: "category.title", media: "featuredImage" },
  },
});
