import { defineField, defineType } from "sanity";

const socialPlatformOptions = [
  { title: "Facebook", value: "facebook" },
  { title: "Instagram", value: "instagram" },
];

const socialStatusOptions = [
  { title: "Not requested", value: "not-requested" },
  { title: "Queued", value: "queued" },
  { title: "Publishing", value: "publishing" },
  { title: "Published", value: "published" },
  { title: "Failed", value: "failed" },
  { title: "Skipped", value: "skipped" },
];

const preparationStatusOptions = [
  { title: "Not prepared", value: "not-prepared" },
  { title: "Preparing", value: "preparing" },
  { title: "Ready", value: "ready" },
  { title: "Needs attention", value: "needs-attention" },
  { title: "Failed", value: "failed" },
];

const checkStatusOptions = [
  { title: "Passed", value: "passed" },
  { title: "Warning", value: "warning" },
  { title: "Failed", value: "failed" },
];

const publicationCheckFields = [
  defineField({ name: "code", title: "Code", type: "string", validation: (rule) => rule.required() }),
  defineField({ name: "title", title: "Check", type: "string", validation: (rule) => rule.required() }),
  defineField({
    name: "status",
    title: "Status",
    type: "string",
    options: { list: checkStatusOptions },
    validation: (rule) => rule.required(),
  }),
  defineField({ name: "message", title: "Message", type: "text", rows: 3 }),
  defineField({ name: "autoFixed", title: "Automatically fixed", type: "boolean", initialValue: false }),
];

export const socialPublishingFields = [
  defineField({
    name: "doNotPublishToSocial",
    title: "Skip automatic social distribution",
    type: "boolean",
    initialValue: false,
    description:
      "Exception override only. Article approval also approves automatic Facebook and Instagram distribution. Enable this only when the article must not be promoted socially.",
  }),
  defineField({
    name: "publicationPreparation",
    title: "Publication preview and readiness",
    type: "object",
    readOnly: true,
    description:
      "Automatic website, Facebook, Instagram, SEO and accessibility preparation generated after editorial approval. This is not a second approval step.",
    fields: [
      defineField({
        name: "status",
        title: "Status",
        type: "string",
        initialValue: "not-prepared",
        options: { list: preparationStatusOptions, layout: "radio" },
      }),
      defineField({ name: "preparedAt", title: "Prepared at", type: "datetime" }),
      defineField({ name: "articleRevision", title: "Article revision", type: "string" }),
      defineField({ name: "websitePreviewUrl", title: "Website preview URL", type: "url" }),
      defineField({ name: "selectedWebsiteImageUrl", title: "Selected website image", type: "url" }),
      defineField({ name: "selectedFacebookImageUrl", title: "Selected Facebook image", type: "url" }),
      defineField({ name: "selectedInstagramImageUrl", title: "Selected Instagram image", type: "url" }),
      defineField({ name: "selectedImageAltText", title: "Selected image alt text", type: "string" }),
      defineField({ name: "facebookSnippet", title: "Facebook preview", type: "text", rows: 4 }),
      defineField({ name: "instagramSnippet", title: "Instagram preview", type: "text", rows: 5 }),
      defineField({ name: "seoScore", title: "SEO score", type: "number", validation: (rule) => rule.min(0).max(100) }),
      defineField({ name: "accessibilityScore", title: "Accessibility score", type: "number", validation: (rule) => rule.min(0).max(100) }),
      defineField({ name: "socialReadinessScore", title: "Social readiness score", type: "number", validation: (rule) => rule.min(0).max(100) }),
      defineField({
        name: "checks",
        title: "Publication checks",
        type: "array",
        of: [{ type: "object", fields: publicationCheckFields }],
      }),
      defineField({ name: "lastError", title: "Last error", type: "text", rows: 3 }),
    ],
  }),
  defineField({
    name: "socialPublishing",
    title: "Social publishing",
    type: "object",
    fields: [
      defineField({
        name: "status",
        title: "Status",
        type: "string",
        initialValue: "not-requested",
        options: { list: socialStatusOptions, layout: "radio" },
        readOnly: true,
      }),
      defineField({
        name: "eventId",
        title: "Event ID",
        type: "string",
        readOnly: true,
        description: "Stable idempotency key generated by the publishing workflow.",
      }),
      defineField({ name: "requestedAt", title: "Requested at", type: "datetime", readOnly: true }),
      defineField({ name: "publishedAt", title: "Published at", type: "datetime", readOnly: true }),
      defineField({ name: "attemptCount", title: "Attempt count", type: "number", initialValue: 0, readOnly: true }),
      defineField({ name: "lastAttemptAt", title: "Last attempt at", type: "datetime", readOnly: true }),
      defineField({ name: "lastError", title: "Last error", type: "text", rows: 3, readOnly: true }),
      defineField({
        name: "posts",
        title: "Published posts",
        type: "array",
        readOnly: true,
        of: [
          {
            type: "object",
            fields: [
              defineField({ name: "platform", title: "Platform", type: "string", options: { list: socialPlatformOptions } }),
              defineField({ name: "postId", title: "Post ID", type: "string" }),
              defineField({ name: "postUrl", title: "Post URL", type: "url" }),
              defineField({ name: "publishedAt", title: "Published at", type: "datetime" }),
            ],
            preview: { select: { title: "platform", subtitle: "postId" } },
          },
        ],
      }),
    ],
  }),
];

export const socialPublishEventType = defineType({
  name: "socialPublishEvent",
  title: "Social Publish Events",
  type: "document",
  readOnly: true,
  fields: [
    defineField({ name: "eventId", title: "Event ID", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "article", title: "Article", type: "reference", to: [{ type: "article" }], validation: (rule) => rule.required() }),
    defineField({ name: "articleRevision", title: "Article revision", type: "string" }),
    defineField({ name: "articleUrl", title: "Article URL", type: "url", validation: (rule) => rule.required() }),
    defineField({ name: "websitePreviewUrl", title: "Website preview URL", type: "url" }),
    defineField({ name: "headline", title: "Headline", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "standfirst", title: "Standfirst", type: "text", rows: 3 }),
    defineField({ name: "selectedWebsiteImageUrl", title: "Selected website image", type: "url" }),
    defineField({
      name: "imageUrl",
      title: "Facebook image URL",
      type: "url",
      description: "Required public image URL. Text-only article promotion is not permitted.",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "instagramImageUrl",
      title: "Instagram image URL",
      type: "url",
      description: "May differ from Facebook when AI selection or platform crop optimisation chooses a stronger asset.",
      validation: (rule) => rule.required(),
    }),
    defineField({ name: "imageAltText", title: "Image alt text", type: "string", validation: (rule) => rule.required() }),
    defineField({
      name: "facebookSnippet",
      title: "Facebook snippet",
      type: "text",
      rows: 4,
      description: "Automatically generated teaser that links readers back to the article.",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "instagramSnippet",
      title: "Instagram snippet",
      type: "text",
      rows: 5,
      description: "Automatically generated caption derived from the approved article and including the article call to action.",
      validation: (rule) => rule.required(),
    }),
    defineField({ name: "seoScore", title: "SEO score", type: "number" }),
    defineField({ name: "accessibilityScore", title: "Accessibility score", type: "number" }),
    defineField({ name: "socialReadinessScore", title: "Social readiness score", type: "number" }),
    defineField({
      name: "checks",
      title: "Publication checks",
      type: "array",
      of: [{ type: "object", fields: publicationCheckFields }],
    }),
    defineField({ name: "requestedAt", title: "Requested at", type: "datetime", validation: (rule) => rule.required() }),
    defineField({
      name: "platforms",
      title: "Platforms",
      type: "array",
      of: [{ type: "string" }],
      options: { list: socialPlatformOptions },
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "status",
      title: "Status",
      type: "string",
      options: { list: socialStatusOptions },
      initialValue: "queued",
      validation: (rule) => rule.required(),
    }),
    defineField({ name: "attemptCount", title: "Attempt count", type: "number", initialValue: 0 }),
    defineField({ name: "lastAttemptAt", title: "Last attempt at", type: "datetime" }),
    defineField({ name: "lastError", title: "Last error", type: "text", rows: 4 }),
    defineField({
      name: "posts",
      title: "Published posts",
      type: "array",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "platform", title: "Platform", type: "string", options: { list: socialPlatformOptions } }),
            defineField({ name: "postId", title: "Post ID", type: "string" }),
            defineField({ name: "postUrl", title: "Post URL", type: "url" }),
            defineField({ name: "publishedAt", title: "Published at", type: "datetime" }),
          ],
        },
      ],
    }),
  ],
  preview: {
    select: { title: "headline", status: "status", requestedAt: "requestedAt" },
    prepare({ title, status, requestedAt }) {
      return { title, subtitle: [status, requestedAt].filter(Boolean).join(" · ") };
    },
  },
});
