import { defineField, defineType } from "sanity";

const socialPlatformOptions = [
  { title: "Facebook", value: "facebook" },
  { title: "Instagram", value: "instagram" },
];

const socialStatusOptions = [
  { title: "Not requested", value: "not-requested" },
  { title: "Queued", value: "queued" },
  { title: "Publishing", value: "publishing" },
  { title: "Published", value: "published" },
  { title: "Failed", value: "failed" },
  { title: "Skipped", value: "skipped" },
];

export const socialPublishingFields = [
  defineField({
    name: "doNotPublishToSocial",
    title: "Do not publish to social",
    type: "boolean",
    initialValue: false,
    description:
      "Editorial override. When enabled, publishing the article must not trigger Facebook or Instagram distribution.",
  }),
  defineField({
    name: "socialPublishing",
    title: "Social publishing",
    type: "object",
    fields: [
      defineField({
        name: "status",
        title: "Status",
        type: "string",
        initialValue: "not-requested",
        options: { list: socialStatusOptions, layout: "radio" },
        readOnly: true,
      }),
      defineField({
        name: "eventId",
        title: "Event ID",
        type: "string",
        readOnly: true,
        description: "Stable idempotency key generated by the publishing workflow.",
      }),
      defineField({
        name: "requestedAt",
        title: "Requested at",
        type: "datetime",
        readOnly: true,
      }),
      defineField({
        name: "publishedAt",
        title: "Published at",
        type: "datetime",
        readOnly: true,
      }),
      defineField({
        name: "attemptCount",
        title: "Attempt count",
        type: "number",
        initialValue: 0,
        readOnly: true,
      }),
      defineField({
        name: "lastAttemptAt",
        title: "Last attempt at",
        type: "datetime",
        readOnly: true,
      }),
      defineField({
        name: "lastError",
        title: "Last error",
        type: "text",
        rows: 3,
        readOnly: true,
      }),
      defineField({
        name: "posts",
        title: "Published posts",
        type: "array",
        readOnly: true,
        of: [
          {
            type: "object",
            fields: [
              defineField({
                name: "platform",
                title: "Platform",
                type: "string",
                options: { list: socialPlatformOptions },
              }),
              defineField({ name: "postId", title: "Post ID", type: "string" }),
              defineField({ name: "postUrl", title: "Post URL", type: "url" }),
              defineField({ name: "publishedAt", title: "Published at", type: "datetime" }),
            ],
            preview: {
              select: {
                title: "platform",
                subtitle: "postId",
              },
            },
          },
        ],
      }),
    ],
  }),
];

export const socialPublishEventType = defineType({
  name: "socialPublishEvent",
  title: "Social Publish Events",
  type: "document",
  readOnly: true,
  fields: [
    defineField({ name: "eventId", title: "Event ID", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "article", title: "Article", type: "reference", to: [{ type: "article" }], validation: (rule) => rule.required() }),
    defineField({ name: "articleRevision", title: "Article revision", type: "string" }),
    defineField({ name: "articleUrl", title: "Article URL", type: "url", validation: (rule) => rule.required() }),
    defineField({ name: "headline", title: "Headline", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "standfirst", title: "Standfirst", type: "text", rows: 3 }),
    defineField({ name: "imageUrl", title: "Image URL", type: "url" }),
    defineField({ name: "requestedAt", title: "Requested at", type: "datetime", validation: (rule) => rule.required() }),
    defineField({
      name: "platforms",
      title: "Platforms",
      type: "array",
      of: [{ type: "string" }],
      options: { list: socialPlatformOptions },
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "status",
      title: "Status",
      type: "string",
      options: { list: socialStatusOptions },
      initialValue: "queued",
      validation: (rule) => rule.required(),
    }),
    defineField({ name: "attemptCount", title: "Attempt count", type: "number", initialValue: 0 }),
    defineField({ name: "lastAttemptAt", title: "Last attempt at", type: "datetime" }),
    defineField({ name: "lastError", title: "Last error", type: "text", rows: 4 }),
    defineField({
      name: "posts",
      title: "Published posts",
      type: "array",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "platform", title: "Platform", type: "string", options: { list: socialPlatformOptions } }),
            defineField({ name: "postId", title: "Post ID", type: "string" }),
            defineField({ name: "postUrl", title: "Post URL", type: "url" }),
            defineField({ name: "publishedAt", title: "Published at", type: "datetime" }),
          ],
        },
      ],
    }),
  ],
  preview: {
    select: {
      title: "headline",
      status: "status",
      requestedAt: "requestedAt",
    },
    prepare({ title, status, requestedAt }) {
      return {
        title,
        subtitle: [status, requestedAt].filter(Boolean).join(" · "),
      };
    },
  },
});
