name: Deploy Sanity Studio

on:
  workflow_dispatch:

jobs:
  deploy-studio:
    runs-on: ubuntu-latest
    env:
      SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.12"

      - name: Install dependencies
        run: npm install

      - name: Deploy Studio
        run: npx sanity deploy therugbypanda --yes
